name: main

on:
  push:
    branches: [main, test-me-*]
    tags: '*'
  pull_request:

jobs:
  main-windows:
    uses: taymurian/workflows/.github/workflows/tox.yml@v1.6.0
    with:
      env: '["py310", "py311", "py312"]'
      os: windows-latest
  main-linux:
    uses: taymurian/workflows/.github/workflows/tox.yml@v1.6.0
    with:
      env: '["py310", "py311", "py312"]'
      os: ubuntu-latest
